# Generated by Django 3.2.4 on 2021-06-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='catagory',
            new_name='category',
        ),
    ]
